title: Mood board
hero_image: images/banner.png
description: mood-board description
version: 4
listed: false
copyedit: false
last_tested: "2022-05-24"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
