name: 'Happiness mood board'
identifier: 'happiness-mood-board'
type: 'html'
components:
  - name: 'index'
    extension: 'html'
    location: index.html
    index: 0
    default: true
  - name: 'animation'
    extension: 'css'
    location: animation.css
    index: 1
    default: false    
  - name: 'style'
    extension: 'css'
    location: style.css
    index: 2
    default: false
  - name: 'default'
    extension: 'css'
    location: default.css
    index: 3
    default: false
  - name: 'woodland'
    extension: 'css'
    location: woodland.css
    index: 4
    default: false    
  - name: 'cafe'
    extension: 'css'
    location: cafe.css
    index: 5
    default: false
  - name: 'comic'
    extension: 'css'
    location: comic.css
    index: 6
    default: false
  - name: 'companion'
    extension: 'css'
    location: companion.css
    index: 7
    default: false
  - name: 'disco'
    extension: 'css'
    location: disco.css
    index: 8
    default: false
  - name: 'festival'
    extension: 'css'
    location: festival.css
    index: 9
    default: false
  - name: 'fiesta'
    extension: 'css'
    location: fiest.css
    index: 10
    default: false
  - name: 'helpful_plumber'
    extension: 'css'
    location: 'helpful_plumber.css'
    index: 11
    default: false
  - name: 'land_animals'
    extension: 'css'
    location: 'land_animals.css'
    index: 12
    default: false
  - name: 'medals'
    extension: 'css'
    location: medals.css
    index: 13
    default: false
  - name: 'money'
    extension: 'css'
    location: money.css
    index: 14
    default: false
  - name: 'nature'
    extension: 'css'
    location: nature.css
    index: 15
    default: false
  - name: 'pastel'
    extension: 'css'
    location: pastel.css
    index: 16
    default: false
  - name: 'primary'
    extension: 'css'
    location: primary.css
    index: 17
    default: false
  - name: 'smokey'
    extension: 'css'
    location: smokey.css
    index: 18
    default: false
  - name: 'space'
    extension: 'css'
    location: space.css
    index: 19
    default: false
  - name: 'sunset'
    extension: 'css'
    location: sunset.css
    index: 20
    default: false
  - name: 'sunshine'
    extension: 'css'
    location: sunshine.css
    index: 21
    default: false
  - name: 'thriller'
    extension: 'css'
    location: thriller.css
    index: 22
    default: false
  - name: 'water-animals'
    extension: 'css'
    location: 'water_animals.css'
    index: 23
    default: false
image:
  - "sunflowers.jpeg"
  - "placeholder.png"
  - "duck.jpg"
  - "beach.jpg"
  - "oranges.jpeg"



